spring:
  application:
    name: library
  datasource:
#    platform: postgres
    url: ${URL_DATABASE:jdbc:postgresql://localhost:5432/library_db}
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL81Dialect

server:
  port: 8080

key: ABCDabcd1234

