####
GET http://localhost:7878/v1/api/authors
Content-Type: application/json


####
GET http://localhost:7878/v1/api/authors/2
Content-Type: application/json


####
POST http://localhost:7878/v1/api/authors
Content-Type: application/json

{
  "name":"Ken Follet"
}
