#####
GET http://localhost:7878/v1/api/book/category/paginate?page=0&size=1
Content-Type: application/json


####
GET http://localhost:7878/v1/api/book/category
Content-Type: application/json


####
GET http://localhost:7878/v1/api/book/category/2
Content-Type: application/json


####
POST http://localhost:7878/v1/api/book/category
Content-Type: application/json

{
  "bookId":"1",
  "categoryId":"15"

}
