####
GET http://localhost:8080/v1/api/categories
Content-Type: application/json


####
GET http://localhost:8080/v1/api/categories/2
Content-Type: application/json


####
POST http://localhost:8080/v1/api/categories
Content-Type: application/json

{
  "category":"Science - Fiction"
}
