#####
GET http://localhost:8080/v1/api/editorial/paginate?page=0&size=10
Content-Type: application/json


####
GET http://localhost:8080/v1/api/editorial
Content-Type: application/json


####
GET http://localhost:8080/v1/api/editorial/2
Content-Type: application/json


####
POST http://localhost:8080/v1/api/editorial
Content-Type: application/json

{
  "editorial":"DEF"
}
