insert into author (author_id, name)values (1,'J.K.Rowling');
insert into author (author_id, name)values (2,'Jojo Moyes');
insert into author (author_id, name)values (3,'Rick Yancey');
insert into author (author_id, name)values (4,'Cassandra Clare');
insert into author (author_id, name)values (5,'J.R.R. Tolkien');
insert into author (author_id, name)values (6,'Lewis Carroll');
insert into author (author_id, name)values (7,'C.S. Lewis');
insert into author (author_id, name)values (8,'Stephen King');
insert into author (author_id, name)values (9,'Markus Zusak');
insert into author (author_id, name)values (10,'John Green');
insert into author (author_id, name)values (11,'Nicola Yoon');
insert into author (author_id, name)values (12,'Lucy Maud Montgomery');
insert into author (author_id, name)values (13,'Miguel de Cervantes');
insert into author (author_id, name)values (14,'Suzanne Collins');
insert into author (author_id, name)values (15,'Veronica Roth');
insert into author (author_id, name)values (16,'Frank Herbert');
insert into author (author_id, name)values (17,'Gabriel Garcia Marquez');
insert into author (author_id, name)values (18,'Dan Brown');
insert into author (author_id, name)values (19,'Douglas Adams');
insert into author (author_id, name)values (20,'Ken Follet');