insert into category (category_id, category)values (1,'Comics');
insert into category (category_id, category)values (2,'Cientifico');
insert into category (category_id, category)values (3,'Autoayuda');
insert into category (category_id, category)values (4,'Ficcion de aventura');
insert into category (category_id, category)values (5,'Ciencia Ficcion');
insert into category (category_id, category)values (6,'Cuentos');
insert into category (category_id, category)values (7,'Humor');
insert into category (category_id, category)values (8,'Suspenso');
insert into category (category_id, category)values (9,'Terror');
insert into category (category_id, category)values (10,'Novela Historica');
insert into category (category_id, category)values (11,'Novela negra');
insert into category (category_id, category)values (12,'Novela');
insert into category (category_id, category)values (13,'Novela Romantica');
insert into category (category_id, category)values (14,'Ficion adulto joven');
insert into category (category_id, category)values (15,'Literatura Infantil');
insert into category (category_id, category)values (16,'Fantasia');
insert into category (category_id, category)values (17,'Fantasia Heroica');
insert into category (category_id, category)values (18,'Thriller');
insert into category (category_id, category)values (19,'Misterio');
insert into category (category_id, category)values (20,'Realismo Magico');
insert into category (category_id, category)values (21,'Ficcion');
insert into category (category_id, category)values (22,'Drama');
