insert into editorial (editorial_id, editorial)values (1,'Acantilado');
insert into editorial (editorial_id, editorial)values (2,'Aguilar');
insert into editorial (editorial_id, editorial)values (3,'Akal');
insert into editorial (editorial_id, editorial)values (4,'Alba');
insert into editorial (editorial_id, editorial)values (5,'Alfaguara');
insert into editorial (editorial_id, editorial)values (6,'Alianza');
insert into editorial (editorial_id, editorial)values (7,'Almadia');
insert into editorial (editorial_id, editorial)values (8,'Anagrama');
insert into editorial (editorial_id, editorial)values (9,'Alpha Decay');
insert into editorial (editorial_id, editorial)values (10,'Ariel');
insert into editorial (editorial_id, editorial)values (11,'Atalanta');
insert into editorial (editorial_id, editorial)values (12,'Caja Negra');
insert into editorial (editorial_id, editorial)values (13,'Catedra');
insert into editorial (editorial_id, editorial)values (14,'Critica');
insert into editorial (editorial_id, editorial)values (15,'Debolsillo');
insert into editorial (editorial_id, editorial)values (16,'Galaxia Gutenberg');
insert into editorial (editorial_id, editorial)values (17,'Gallo Nero');
insert into editorial (editorial_id, editorial)values (18,'Gredos');
insert into editorial (editorial_id, editorial)values (19,'Gustavo Gili');
insert into editorial (editorial_id, editorial)values (20,'Herder');
insert into editorial (editorial_id, editorial)values (21,'Impedimenta');
insert into editorial (editorial_id, editorial)values (22,'Joaquin Mortiz');
insert into editorial (editorial_id, editorial)values (23,'La esfera de los libros');
insert into editorial (editorial_id, editorial)values (24,'Library of America');
insert into editorial (editorial_id, editorial)values (25,'Lumen');
insert into editorial (editorial_id, editorial)values (26,'Nevsky');
insert into editorial (editorial_id, editorial)values (27,'Olatena');
insert into editorial (editorial_id, editorial)values (28,'Paidos');
insert into editorial (editorial_id, editorial)values (29,'Penguin Books');
insert into editorial (editorial_id, editorial)values (30,'Phaidon');
insert into editorial (editorial_id, editorial)values (31,'Planeta');
insert into editorial (editorial_id, editorial)values (32,'Plaza y janes');
insert into editorial (editorial_id, editorial)values (33,'RM');
insert into editorial (editorial_id, editorial)values (34,'Sajalin');
insert into editorial (editorial_id, editorial)values (35,'Salamandra');
insert into editorial (editorial_id, editorial)values (36,'Satori');
insert into editorial (editorial_id, editorial)values (37,'Seix Barral');
insert into editorial (editorial_id, editorial)values (38,'Sexto Piso');
insert into editorial (editorial_id, editorial)values (39,'Siglo XXI');
insert into editorial (editorial_id, editorial)values (40,'Siruela');
insert into editorial (editorial_id, editorial)values (41,'Taschen');
insert into editorial (editorial_id, editorial)values (42,'Taurus');
insert into editorial (editorial_id, editorial)values (43,'Trotta');
insert into editorial (editorial_id, editorial)values (44,'Tusquets');
insert into editorial (editorial_id, editorial)values (45,'Urano');
insert into editorial (editorial_id, editorial)values (46,'Valdemar');